name: Deploy LLAMA Bundle Demo

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: "testRG"
  CLUSTER_NAME: "myTestCluster"

jobs:
  build:
    permissions:
      actions: read
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@master

      - name: Azure Login
        uses: azure/login@v1.4.3
        with:
          client-id: ${{ secrets.AZURE_CLIENT }}
          client-secret: ${{ secrets.AZURE_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
          
      - name: Get K8S Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      # Deploys application based on given manifest file
      - name: Deploys application
        uses: Azure/k8s-deploy@v3.0
        with:
          action: deploy
          namespace: k8sdev
          manifests: |
            manifests/llama.yaml
